### ISSUE TITLE
encrypting the shared keys

### ISSUE THREAD

**Issue by justpoliz** [csyezheng/a2fa#1]
### Use case:
One-time passwords can be easily calculated if the secret  key is compromised

### Proposal:
It is recommend to encrypt the shared secrets

### Current behaviour:
Currently secret keys are stored in clear text in the database.

### Desired behaviour:
Storing the keys securely by encrypting them with tamper-resistant hardware encryption

### Alternatives considered:
Using the user’s password to encrypt the secret keys

**Comment by csyezheng** [comment]
@justpoliz 

As long as your localhost is secure, there is no need for an encryption key.

It's not a good idea to use user passwords to encrypt keys, if someone resets their password they have to regenerate their secret as well.

Of course, for key encryption, this is an enhanced feature that may be supported in the future. I'm also thinking about how to encrypt the key

**Comment by zQueal** [comment]
> It's not a good idea to use user passwords to encrypt keys

Perhaps something like [age](https://github.com/FiloSottile/age)?

**Comment by xiconet** [comment]
Thanks for providing your nice software for free. 2FA everywhere is indeed annoying. However I also think that (optional) keys encryption would be a nice feature to add for some extra paranoia.
