### ISSUE TITLE
生成的密码和谷歌身份验证器对不上

### ISSUE THREAD

**Issue by enpin753** [csyezheng/a2fa#2]
```
a2fa generate "sjty rbgo 56og 37kj sz6s ry2c t3l3 pm5p"
```
输出
Code: 358511

谷歌身份验证器同一时间是 919019

**Comment by csyezheng** [comment]
@enpin753 

空格不是 base32 的一部分。只需删除空格并将字母变为大写即可。 
在linux下用命令转换或者用在线工具转换
```
echo "sjty rbgo 56og 37kj sz6s ry2c t3l3 pm5p" | sed  s/\ //g | tr a-z A-Z
```
下一个版本会增加支持空格和小写字母，自动去除空格并转换为大写

**Comment by csyezheng** [comment]
已添加支持自动去除空格并转换为大写

[Added support for automatically stripping spaces and converting to uppercase](https://github.com/csyezheng/a2fa/commit/12da6b47441f317cf617078c35b726184e14491a)
