### ISSUE TITLE
leading zeros are missing for the generated verification code

### ISSUE THREAD

**Issue by blazeoffire0** [csyezheng/a2fa#3]
### Steps to reproduce
```
a2fa generate xxxxxxxxx
```
### Expected behaviour
003269

### Actual behaviour
3269

**Comment by csyezheng** [comment]
@blazeoffire0 

This bug has been fixed
[fix the error of missing the leading zero in the code; update version](https://github.com/csyezheng/a2fa/commit/e098c0ff5ffd83cdc754ca755aa870872433a44e)
